// <auto-generated />
using System;
using ARABAZON.TradeAI.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ARABAZON.TradeAI.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526004039_AddRiskTables")]
    partial class AddRiskTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ARABAZON.TradeAI.Domain.Entities.Candle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OpenTime");

                    b.HasIndex("SymbolId", "Timeframe", "OpenTime");

                    b.ToTable("Candles");
                });

            modelBuilder.Entity("ARABAZON.TradeAI.Domain.Entities.Indicator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CandleId")
                        .HasColumnType("bigint");

                    b.Property<string>("IndicatorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("CandleId", "IndicatorType")
                        .IsUnique();

                    b.ToTable("Indicators");
                });

            modelBuilder.Entity("ARABAZON.TradeAI.Domain.Entities.MarketSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AskPrice")
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)");

                    b.Property<decimal>("BidPrice")
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Spread")
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Volatility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId", "SnapshotTime");

                    b.ToTable("MarketSnapshots");
                });

            modelBuilder.Entity("ARABAZON.TradeAI.Domain.Entities.RiskConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoTradingEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyLossLimit")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxConcurrentTrades")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxExposure")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxRiskPerTrade")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RiskConfigurations");
                });

            modelBuilder.Entity("ARABAZON.TradeAI.Domain.Entities.RiskEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CurrentValue")
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ThresholdValue")
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("TriggeredAt");

                    b.ToTable("RiskEvents");
                });

            modelBuilder.Entity("ARABAZON.TradeAI.Domain.Entities.Symbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ContractSize")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("boolean");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SymbolCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SymbolCode")
                        .IsUnique();

                    b.ToTable("Symbols");
                });

            modelBuilder.Entity("ARABAZON.TradeAI.Domain.Entities.SymbolRiskConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AtrMultiplierSL")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("AtrMultiplierTP")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("AutoTradingEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrentTrades")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxDailyLoss")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("MaxPositionSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("MaxRiskPerTrade")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("MaxSlippageAllowed")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.Property<decimal>("MaxSpreadAllowed")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId")
                        .IsUnique();

                    b.ToTable("SymbolRiskConfigurations");
                });

            modelBuilder.Entity("ARABAZON.TradeAI.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrokerTicket")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PositionSize")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SignalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OpenedAt");

                    b.HasIndex("Status");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("ARABAZON.TradeAI.Domain.Entities.TradeSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("Status");

                    b.ToTable("TradeSignals");
                });

            modelBuilder.Entity("ARABAZON.TradeAI.Domain.Entities.Candle", b =>
                {
                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Price", "ClosePrice", b1 =>
                        {
                            b1.Property<long>("CandleId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 5)
                                .HasColumnType("numeric(18,5)")
                                .HasColumnName("ClosePrice");

                            b1.HasKey("CandleId");

                            b1.ToTable("Candles");

                            b1.WithOwner()
                                .HasForeignKey("CandleId");
                        });

                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Price", "HighPrice", b1 =>
                        {
                            b1.Property<long>("CandleId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 5)
                                .HasColumnType("numeric(18,5)")
                                .HasColumnName("HighPrice");

                            b1.HasKey("CandleId");

                            b1.ToTable("Candles");

                            b1.WithOwner()
                                .HasForeignKey("CandleId");
                        });

                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Price", "LowPrice", b1 =>
                        {
                            b1.Property<long>("CandleId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 5)
                                .HasColumnType("numeric(18,5)")
                                .HasColumnName("LowPrice");

                            b1.HasKey("CandleId");

                            b1.ToTable("Candles");

                            b1.WithOwner()
                                .HasForeignKey("CandleId");
                        });

                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Price", "OpenPrice", b1 =>
                        {
                            b1.Property<long>("CandleId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 5)
                                .HasColumnType("numeric(18,5)")
                                .HasColumnName("OpenPrice");

                            b1.HasKey("CandleId");

                            b1.ToTable("Candles");

                            b1.WithOwner()
                                .HasForeignKey("CandleId");
                        });

                    b.Navigation("ClosePrice")
                        .IsRequired();

                    b.Navigation("HighPrice")
                        .IsRequired();

                    b.Navigation("LowPrice")
                        .IsRequired();

                    b.Navigation("OpenPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("ARABAZON.TradeAI.Domain.Entities.Trade", b =>
                {
                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Price", "EntryPrice", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 5)
                                .HasColumnType("numeric(18,5)")
                                .HasColumnName("EntryPrice");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Price", "ExitPrice", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 5)
                                .HasColumnType("numeric(18,5)")
                                .HasColumnName("ExitPrice");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Price", "StopLoss", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 5)
                                .HasColumnType("numeric(18,5)")
                                .HasColumnName("StopLoss");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Price", "TakeProfit", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 5)
                                .HasColumnType("numeric(18,5)")
                                .HasColumnName("TakeProfit");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Money", "ProfitLoss", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("ProfitLossAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("ProfitLossCurrency");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.Navigation("EntryPrice")
                        .IsRequired();

                    b.Navigation("ExitPrice");

                    b.Navigation("ProfitLoss")
                        .IsRequired();

                    b.Navigation("StopLoss")
                        .IsRequired();

                    b.Navigation("TakeProfit")
                        .IsRequired();
                });

            modelBuilder.Entity("ARABAZON.TradeAI.Domain.Entities.TradeSignal", b =>
                {
                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Percentage", "ConfidenceScore", b1 =>
                        {
                            b1.Property<Guid>("TradeSignalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("ConfidenceScore");

                            b1.HasKey("TradeSignalId");

                            b1.ToTable("TradeSignals");

                            b1.WithOwner()
                                .HasForeignKey("TradeSignalId");
                        });

                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Price", "EntryPrice", b1 =>
                        {
                            b1.Property<Guid>("TradeSignalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 5)
                                .HasColumnType("numeric(18,5)")
                                .HasColumnName("EntryPrice");

                            b1.HasKey("TradeSignalId");

                            b1.ToTable("TradeSignals");

                            b1.WithOwner()
                                .HasForeignKey("TradeSignalId");
                        });

                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Percentage", "RiskPercentage", b1 =>
                        {
                            b1.Property<Guid>("TradeSignalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("RiskPercentage");

                            b1.HasKey("TradeSignalId");

                            b1.ToTable("TradeSignals");

                            b1.WithOwner()
                                .HasForeignKey("TradeSignalId");
                        });

                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Price", "StopLoss", b1 =>
                        {
                            b1.Property<Guid>("TradeSignalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 5)
                                .HasColumnType("numeric(18,5)")
                                .HasColumnName("StopLoss");

                            b1.HasKey("TradeSignalId");

                            b1.ToTable("TradeSignals");

                            b1.WithOwner()
                                .HasForeignKey("TradeSignalId");
                        });

                    b.OwnsOne("ARABAZON.TradeAI.Domain.ValueObjects.Price", "TakeProfit", b1 =>
                        {
                            b1.Property<Guid>("TradeSignalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 5)
                                .HasColumnType("numeric(18,5)")
                                .HasColumnName("TakeProfit");

                            b1.HasKey("TradeSignalId");

                            b1.ToTable("TradeSignals");

                            b1.WithOwner()
                                .HasForeignKey("TradeSignalId");
                        });

                    b.Navigation("ConfidenceScore")
                        .IsRequired();

                    b.Navigation("EntryPrice")
                        .IsRequired();

                    b.Navigation("RiskPercentage")
                        .IsRequired();

                    b.Navigation("StopLoss")
                        .IsRequired();

                    b.Navigation("TakeProfit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
